### ISSUE TITLE
Failed to rpmbuild on Suse11 sp4 x86_64

### ISSUE THREAD

**Issue by dfenglei** [gluster/glusterfs-suse#1]
After executing the make glusterrpm command to build the gluster 3.6.8 rpm package for suse11 sp4 x86_64.
The following error messges was found.

error: Installed (but unpackaged) file(s) found:  
   /usr/lib64/python2.6/site-packages/gluster/__init__.py
......

**Comment by kalebskeithley** [comment]
3.6 is EOL and SuSE SLES 11 has never been supported.
