### ISSUE TITLE
glusterfsd daemon not starting during the boot on SuSe 11 sp4 x86_64

### ISSUE THREAD

**Issue by dfenglei** [gluster/glusterfs-suse#3]
after I build and installed the 3.6.8 package on SuSe 11 sp4 x86_64, I reboot the OS and found that glusterfsd did not start.
3.10 and 3.11 have the same issue.

**Comment by kalebskeithley** [comment]
SuSE 11 has never been supported. It doesn't have the necessary prerequisites for building GlusterFS
